# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 30

[[main]]
  name = "Competencies"
  url = "#competencies"
  weight = 20

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 40

#[[main]]
#  name = "Publications"
#  url = "#featured"
#  weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 50

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
[[main]]
  name = "Downloads"
  url = "/download/"
  weight = 60

[[main]]
  parent = "Downloads"
  name = "Detailed CV"
  url = "files/CV_Khan_Nazeer_detailed.pdf"

[[main]]
  parent = "Downloads"
  name = "Overview CV"
  url = "files/CV_Khan_Nazeer_overview.pdf"

[[main]]
  parent = "Downloads"
  name = "Text CV"
  url = "files/CV_Khan_Nazeer_text.txt"
